sonar.projectKey=devops-cicd-security-platform
sonar.projectName=devops-cicd-security-platform
sonar.sources=.
sonar.exclusions=**/reports/**,**/artifacts/**,**/.github/**
sonar.inclusions=**/*.yml,**/*.yaml,**/*.sh,**/*.rego
